import React from 'react'
import FallingFlower from './FallingFlower'

export default function Flower({ top = -50, duration = 20 }) {
    return (
        <div>
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />
            <FallingFlower top={top} duration={duration} />

        </div>
    )
}
